import { createContext } from 'react';

export const AuthContext = createContext({
  currentUser: null,
  userProfile: null,
  loading: true,
  authLoading: true,
  profileLoading: false,
  isAuthenticated: false,
  isAdmin: false,
  isConfigured: false,
  signIn: async () => {},
  signUp: async () => {},
  signInWithGoogle: async () => {},
  signUpAsAdmin: async () => {},
  signInAsAdmin: async () => {},
  signInWithGoogleAsAdmin: async () => {},
  signUpAsInvitedUser: async () => {},
  signInAsInvitedUser: async () => {},
  signInWithGoogleAsInvitedUser: async () => {},
  signOut: async () => {},
  resetPassword: async () => {},
  refreshProfile: async () => {},
  updateProfileData: async () => {},
  deleteAccount: async () => {},
  reauthenticateWithGoogle: async () => {},
});
